public enum UserCondition {
    DOING_NOTHING,
    ENTERING_MODULE,
    ENTERING_TOPIC,
    ENTERING_QUESTION,
    ENTERING_ANSWERS,
    ADDING_MODULE,
    ENTERING_MODULE_FOR_GETTING_TEST,
    ENTERING_TOPIC_FOR_GETTING_TEST,
    SOLVING_TEST,
    ENTERING_LOGIN,
    ENTERING_PASSWORD,
    ENTERING_ACCESS_KEY,
    ANSWERING_IS_ADMIN,
    ENTERING_ACCESS_KEY_AFTER_REGISTRATION,
    ADDING_TOPIC
}
