public enum UserCondition {
    DOING_NOTHING,
    ENTERING_MODULE,
    ENTERING_TOPIC,
    ENTERING_QUESTION,
    SENDING_TEST_NUMBER,
    ENTERING_ANSWERS,
    ADDING_MODULE,
    ENTERING_MODULE_FOR_GETTING_TEST,
    ENTERING_TOPIC_FOR_GETTING_TEST, SOLVING_TEST, ADDING_TOPIC
}
